name: numoonchld
title: numoonchld
plugins:
  - jekyll-sitemap
site.url: https://numoonchld.github.io
twitter_username: rasaralaya
markdown: kramdown
mathjax: true

paginate: 8
paginate_path: "/blog/page:num/"
